/**
 * CI workflow template generators.
 *
 * Each function produces a complete CI configuration string for a specific
 * platform, embedding the user's vibrancy thresholds into the output.
 * Extracted from ci-generator.ts to keep files under the 300-line limit.
 */

import { CiThresholds } from '../types';

/**
 * Generate a GitHub Actions workflow YAML.
 *
 * Produces a workflow that triggers on PRs modifying pubspec files,
 * runs `flutter pub outdated`, and posts a dependency health comment.
 */
export function generateGitHubActions(thresholds: CiThresholds): string {
    const failOnVuln = thresholds.failOnVulnerability ? 'true' : 'false';

    return `# Generated by Saropa Package Vibrancy
# Checks dependency health on PRs that modify pubspec files

name: Dependency Health Check

on:
  pull_request:
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'

jobs:
  vibrancy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Check dependency health
        id: health-check
        run: |
          echo "Checking dependency health thresholds..."

          # Get outdated packages info
          flutter pub outdated --json > outdated.json

          # Parse and check thresholds
          dart run <<'DART_SCRIPT'
          import 'dart:convert';
          import 'dart:io';

          void main() {
            final json = jsonDecode(File('outdated.json').readAsStringSync());
            final packages = json['packages'] as List? ?? [];

            var outdatedCount = 0;
            var majorUpdates = 0;

            for (final pkg in packages) {
              final current = pkg['current']?['version'];
              final latest = pkg['latest']?['version'];
              if (current != null && latest != null && current != latest) {
                outdatedCount++;
                final currentMajor = int.tryParse(current.split('.')[0]) ?? 0;
                final latestMajor = int.tryParse(latest.split('.')[0]) ?? 0;
                if (latestMajor > currentMajor) majorUpdates++;
              }
            }

            print('📊 Dependency Health Summary');
            print('   Outdated packages: \$outdatedCount');
            print('   Major updates available: \$majorUpdates');

            // Thresholds from configuration
            const maxEol = ${thresholds.maxEndOfLife};
            const maxLegacy = ${thresholds.maxLegacyLocked};
            const minAvgVibrancy = ${thresholds.minAverageVibrancy};
            const failOnVuln = ${failOnVuln};

            print('');
            print('   Thresholds:');
            print('     Max EOL: \$maxEol');
            print('     Max Legacy: \$maxLegacy');
            print('     Min Avg Vibrancy: \$minAvgVibrancy');
            print('     Fail on Vulnerability: \$failOnVuln');

            // For full vibrancy checks, use saropa_vibrancy_cli when available
            // This basic check ensures pub outdated runs successfully
          }
          DART_SCRIPT

      - name: Upload dependency report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: outdated.json
          retention-days: 7

      - name: Comment on PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            let report = '## 📊 Dependency Health Check\\n\\n';

            try {
              const outdated = JSON.parse(fs.readFileSync('outdated.json', 'utf8'));
              const packages = outdated.packages || [];
              const outdatedCount = packages.filter(p =>
                p.current?.version && p.latest?.version &&
                p.current.version !== p.latest.version
              ).length;

              report += '| Metric | Value | Threshold | Status |\\n';
              report += '|--------|-------|-----------|--------|\\n';
              report += \`| Outdated | \${outdatedCount} | — | \${outdatedCount === 0 ? '✅' : 'ℹ️'} |\\n\`;
              report += \`| EOL Limit | — | ≤ ${thresholds.maxEndOfLife} | — |\\n\`;
              report += \`| Legacy Limit | — | ≤ ${thresholds.maxLegacyLocked} | — |\\n\`;
              report += \`| Min Avg Vibrancy | — | ≥ ${thresholds.minAverageVibrancy} | — |\\n\`;
              report += '\\n*Full vibrancy analysis requires saropa_vibrancy_cli*\\n';
            } catch (e) {
              report += 'Failed to parse dependency report.\\n';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
`;
}

/**
 * Generate a GitLab CI job configuration YAML.
 *
 * Produces a job that runs on pubspec changes, checks outdated packages,
 * and stores the report as an artifact for one week.
 */
export function generateGitLabCi(thresholds: CiThresholds): string {
    return `# Generated by Saropa Package Vibrancy
# Add this to your .gitlab-ci.yml or include as a separate file

vibrancy-check:
  stage: test
  image: cirrusci/flutter:stable
  rules:
    - changes:
        - pubspec.yaml
        - pubspec.lock
  script:
    - flutter pub get
    - echo "Checking dependency health thresholds..."
    - flutter pub outdated --json > outdated.json
    - |
      dart run <<'DART_SCRIPT'
      import 'dart:convert';
      import 'dart:io';

      void main() {
        final json = jsonDecode(File('outdated.json').readAsStringSync());
        final packages = json['packages'] as List? ?? [];

        var outdatedCount = 0;
        for (final pkg in packages) {
          final current = pkg['current']?['version'];
          final latest = pkg['latest']?['version'];
          if (current != null && latest != null && current != latest) {
            outdatedCount++;
          }
        }

        print('📊 Dependency Health Summary');
        print('   Outdated packages: \$outdatedCount');

        // Thresholds
        print('   Max EOL: ${thresholds.maxEndOfLife}');
        print('   Max Legacy: ${thresholds.maxLegacyLocked}');
        print('   Min Avg Vibrancy: ${thresholds.minAverageVibrancy}');
        print('   Fail on Vulnerability: ${thresholds.failOnVulnerability}');
      }
      DART_SCRIPT
  artifacts:
    paths:
      - outdated.json
    expire_in: 1 week
    when: always
`;
}

/**
 * Generate a portable shell script for manual or custom CI pipelines.
 *
 * Embeds thresholds as shell variables, checks for Flutter on PATH,
 * runs `pub outdated`, and reports results via a Dart inline script.
 */
export function generateShellScript(thresholds: CiThresholds): string {
    const failOnVuln = thresholds.failOnVulnerability ? 'true' : 'false';

    return `#!/bin/bash
# Generated by Saropa Package Vibrancy
# Portable dependency health check script

set -e

# Configuration thresholds
MAX_EOL=${thresholds.maxEndOfLife}
MAX_LEGACY=${thresholds.maxLegacyLocked}
MIN_AVG_VIBRANCY=${thresholds.minAverageVibrancy}
FAIL_ON_VULN=${failOnVuln}

echo "📊 Dependency Health Check"
echo "=========================="
echo ""

# Ensure Flutter is available
if ! command -v flutter &> /dev/null; then
    echo "❌ Flutter not found in PATH"
    exit 1
fi

# Install dependencies
echo "Installing dependencies..."
flutter pub get

# Get outdated packages
echo "Checking for outdated packages..."
flutter pub outdated --json > /tmp/outdated.json

# Parse results with Dart
dart run <<'DART_SCRIPT'
import 'dart:convert';
import 'dart:io';

void main() {
  final json = jsonDecode(File('/tmp/outdated.json').readAsStringSync());
  final packages = json['packages'] as List? ?? [];

  var outdatedCount = 0;
  var majorUpdates = 0;
  final outdatedList = <String>[];

  for (final pkg in packages) {
    final name = pkg['package'] as String?;
    final current = pkg['current']?['version'];
    final latest = pkg['latest']?['version'];

    if (current != null && latest != null && current != latest) {
      outdatedCount++;
      outdatedList.add('  - \$name: \$current → \$latest');

      final currentMajor = int.tryParse(current.split('.')[0]) ?? 0;
      final latestMajor = int.tryParse(latest.split('.')[0]) ?? 0;
      if (latestMajor > currentMajor) majorUpdates++;
    }
  }

  print('Results:');
  print('  Total packages: \${packages.length}');
  print('  Outdated: \$outdatedCount');
  print('  Major updates: \$majorUpdates');

  if (outdatedList.isNotEmpty) {
    print('');
    print('Outdated packages:');
    for (final item in outdatedList) {
      print(item);
    }
  }

  print('');
  print('Thresholds:');
  print('  Max End-of-Life: ${thresholds.maxEndOfLife}');
  print('  Max Legacy-Locked: ${thresholds.maxLegacyLocked}');
  print('  Min Average Vibrancy: ${thresholds.minAverageVibrancy}');
  print('  Fail on Vulnerability: ${failOnVuln}');

  // Exit codes
  // 0 = pass, 1 = warning, 2 = fail
  // For full vibrancy checks, use saropa_vibrancy_cli when available
}
DART_SCRIPT

echo ""
echo "✅ Dependency check complete"
echo ""
echo "Note: For full vibrancy scoring, install saropa_vibrancy_cli:"
echo "  dart pub global activate saropa_vibrancy_cli"
`;
}
